package com.bupt.rongsell.dao;

import com.bupt.rongsell.entity.Group;
import com.bupt.rongsell.entity.GroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_group_use
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    long countByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_group_use
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    int deleteByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_group_use
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_group_use
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_group_use
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_group_use
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    List<Group> selectByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_group_use
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    Group selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_group_use
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") Group record, @Param("example") GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_group_use
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    int updateByExample(@Param("record") Group record, @Param("example") GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_group_use
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    int updateByPrimaryKeySelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_group_use
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    int updateByPrimaryKey(Group record);

    /**
     * 获取平级的子分类
     * @param parentId
     * @return
     */
    List<Group> selectParallelChildrenGroup(int parentId);
}
