package com.bupt.rongsell.dao;

import com.bupt.rongsell.entity.Sku;
import com.bupt.rongsell.entity.SkuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface SkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_use
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    long countByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_use
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    int deleteByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_use
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_use
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    int insert(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_use
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    int insertSelective(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_use
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    List<Sku> selectByExampleWithBLOBs(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_use
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    List<Sku> selectByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_use
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    Sku selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_use
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") Sku record, @Param("example") SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_use
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Sku record, @Param("example") SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_use
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    int updateByExample(@Param("record") Sku record, @Param("example") SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_use
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    int updateByPrimaryKeySelective(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_use
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sku_use
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    int updateByPrimaryKey(Sku record);

    /**
     * 查询商品列表
     * @return
     */
    List<Sku> selectSkuList();
}
