package com.bupt.core.entity;

import com.alibaba.fastjson.JSONObject;

public class Hobby {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.id
     *
     * @mbg.generated Thu Jul 02 13:35:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.huahua
     *
     * @mbg.generated Thu Jul 02 13:35:18 CST 2020
     */
    private JSONObject huahua;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.id
     *
     * @return the value of t_test.id
     *
     * @mbg.generated Thu Jul 02 13:35:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.id
     *
     * @param id the value for t_test.id
     *
     * @mbg.generated Thu Jul 02 13:35:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.huahua
     *
     * @return the value of t_test.huahua
     *
     * @mbg.generated Thu Jul 02 13:35:18 CST 2020
     */
    public JSONObject getHuahua() {
        return huahua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.huahua
     *
     * @param huahua the value for t_test.huahua
     *
     * @mbg.generated Thu Jul 02 13:35:18 CST 2020
     */
    public void setHuahua(JSONObject huahua) {
        this.huahua = huahua;
    }

    @Override
    public String toString() {
        return "Hobby{" +
                "id=" + id +
                ", huahua=" + huahua +
                '}';
    }
}
