package com.bupt.core.entity;

import com.alibaba.fastjson.JSONObject;

import java.math.BigDecimal;
import java.util.Date;

public class Sku {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku_use.id
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku_use.spu_id
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    private Integer spuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku_use.title
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku_use.sub_title
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    private String subTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku_use.main_image
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    private String mainImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku_use.price
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku_use.stock
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku_use.param
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    private JSONObject param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku_use.status
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku_use.create_time
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku_use.last_update_time
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku_use.sub_images
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    private String subImages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sku_use.detail
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku_use.id
     *
     * @return the value of t_sku_use.id
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku_use.id
     *
     * @param id the value for t_sku_use.id
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku_use.spu_id
     *
     * @return the value of t_sku_use.spu_id
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public Integer getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku_use.spu_id
     *
     * @param spuId the value for t_sku_use.spu_id
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public void setSpuId(Integer spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku_use.title
     *
     * @return the value of t_sku_use.title
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku_use.title
     *
     * @param title the value for t_sku_use.title
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku_use.sub_title
     *
     * @return the value of t_sku_use.sub_title
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku_use.sub_title
     *
     * @param subTitle the value for t_sku_use.sub_title
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku_use.main_image
     *
     * @return the value of t_sku_use.main_image
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public String getMainImage() {
        return mainImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku_use.main_image
     *
     * @param mainImage the value for t_sku_use.main_image
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public void setMainImage(String mainImage) {
        this.mainImage = mainImage == null ? null : mainImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku_use.price
     *
     * @return the value of t_sku_use.price
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku_use.price
     *
     * @param price the value for t_sku_use.price
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku_use.stock
     *
     * @return the value of t_sku_use.stock
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku_use.stock
     *
     * @param stock the value for t_sku_use.stock
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku_use.param
     *
     * @return the value of t_sku_use.param
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public JSONObject getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku_use.param
     *
     * @param param the value for t_sku_use.param
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public void setParam(JSONObject param) {
        this.param = param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku_use.status
     *
     * @return the value of t_sku_use.status
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku_use.status
     *
     * @param status the value for t_sku_use.status
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku_use.create_time
     *
     * @return the value of t_sku_use.create_time
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku_use.create_time
     *
     * @param createTime the value for t_sku_use.create_time
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku_use.last_update_time
     *
     * @return the value of t_sku_use.last_update_time
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku_use.last_update_time
     *
     * @param lastUpdateTime the value for t_sku_use.last_update_time
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku_use.sub_images
     *
     * @return the value of t_sku_use.sub_images
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public String getSubImages() {
        return subImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku_use.sub_images
     *
     * @param subImages the value for t_sku_use.sub_images
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public void setSubImages(String subImages) {
        this.subImages = subImages == null ? null : subImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sku_use.detail
     *
     * @return the value of t_sku_use.detail
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sku_use.detail
     *
     * @param detail the value for t_sku_use.detail
     *
     * @mbg.generated Thu Jul 02 14:41:55 CST 2020
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    @Override
    public String toString() {
        return "Sku{" +
                "id=" + id +
                ", spuId=" + spuId +
                ", title='" + title + '\'' +
                ", subTitle='" + subTitle + '\'' +
                ", mainImage='" + mainImage + '\'' +
                ", price=" + price +
                ", stock=" + stock +
                ", param=" + param +
                ", status=" + status +
                ", createTime=" + createTime +
                ", lastUpdateTime=" + lastUpdateTime +
                ", subImages='" + subImages + '\'' +
                ", detail='" + detail + '\'' +
                '}';
    }
}
