package com.bupt.core.entity;

import java.util.List;

public class SpecParam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_param_use.id
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_param_use.spg_id
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    private Integer spgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_param_use.spp_id
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    private Integer sppId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_param_use.name
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_param_use.numeric
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    private Byte numeric;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_param_use.unit
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_param_use.generic
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    private Byte generic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_param_use.searching
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    private Byte searching;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_param_use.segements
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    private String segements;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_param_use.value
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    private Integer value;

    List<SpecParam> specParamList;

    public List<SpecParam> getSpecParamList() {
        return specParamList;
    }

    public void setSpecParamList(List<SpecParam> specParamList) {
        this.specParamList = specParamList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_param_use.id
     *
     * @return the value of t_spec_param_use.id
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_param_use.id
     *
     * @param id the value for t_spec_param_use.id
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_param_use.spg_id
     *
     * @return the value of t_spec_param_use.spg_id
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public Integer getSpgId() {
        return spgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_param_use.spg_id
     *
     * @param spgId the value for t_spec_param_use.spg_id
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public void setSpgId(Integer spgId) {
        this.spgId = spgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_param_use.spp_id
     *
     * @return the value of t_spec_param_use.spp_id
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public Integer getSppId() {
        return sppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_param_use.spp_id
     *
     * @param sppId the value for t_spec_param_use.spp_id
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public void setSppId(Integer sppId) {
        this.sppId = sppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_param_use.name
     *
     * @return the value of t_spec_param_use.name
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_param_use.name
     *
     * @param name the value for t_spec_param_use.name
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_param_use.numeric
     *
     * @return the value of t_spec_param_use.numeric
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public Byte getNumeric() {
        return numeric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_param_use.numeric
     *
     * @param numeric the value for t_spec_param_use.numeric
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public void setNumeric(Byte numeric) {
        this.numeric = numeric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_param_use.unit
     *
     * @return the value of t_spec_param_use.unit
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_param_use.unit
     *
     * @param unit the value for t_spec_param_use.unit
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_param_use.generic
     *
     * @return the value of t_spec_param_use.generic
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public Byte getGeneric() {
        return generic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_param_use.generic
     *
     * @param generic the value for t_spec_param_use.generic
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public void setGeneric(Byte generic) {
        this.generic = generic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_param_use.searching
     *
     * @return the value of t_spec_param_use.searching
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public Byte getSearching() {
        return searching;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_param_use.searching
     *
     * @param searching the value for t_spec_param_use.searching
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public void setSearching(Byte searching) {
        this.searching = searching;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_param_use.segements
     *
     * @return the value of t_spec_param_use.segements
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public String getSegements() {
        return segements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_param_use.segements
     *
     * @param segements the value for t_spec_param_use.segements
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public void setSegements(String segements) {
        this.segements = segements == null ? null : segements.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_param_use.value
     *
     * @return the value of t_spec_param_use.value
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_param_use.value
     *
     * @param value the value for t_spec_param_use.value
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public void setValue(Integer value) {
        this.value = value;
    }
}
