package com.bupt.core.entity;

import java.util.ArrayList;
import java.util.List;

public class SpecParamExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public SpecParamExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSpgIdIsNull() {
            addCriterion("spg_id is null");
            return (Criteria) this;
        }

        public Criteria andSpgIdIsNotNull() {
            addCriterion("spg_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpgIdEqualTo(Integer value) {
            addCriterion("spg_id =", value, "spgId");
            return (Criteria) this;
        }

        public Criteria andSpgIdNotEqualTo(Integer value) {
            addCriterion("spg_id <>", value, "spgId");
            return (Criteria) this;
        }

        public Criteria andSpgIdGreaterThan(Integer value) {
            addCriterion("spg_id >", value, "spgId");
            return (Criteria) this;
        }

        public Criteria andSpgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("spg_id >=", value, "spgId");
            return (Criteria) this;
        }

        public Criteria andSpgIdLessThan(Integer value) {
            addCriterion("spg_id <", value, "spgId");
            return (Criteria) this;
        }

        public Criteria andSpgIdLessThanOrEqualTo(Integer value) {
            addCriterion("spg_id <=", value, "spgId");
            return (Criteria) this;
        }

        public Criteria andSpgIdIn(List<Integer> values) {
            addCriterion("spg_id in", values, "spgId");
            return (Criteria) this;
        }

        public Criteria andSpgIdNotIn(List<Integer> values) {
            addCriterion("spg_id not in", values, "spgId");
            return (Criteria) this;
        }

        public Criteria andSpgIdBetween(Integer value1, Integer value2) {
            addCriterion("spg_id between", value1, value2, "spgId");
            return (Criteria) this;
        }

        public Criteria andSpgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("spg_id not between", value1, value2, "spgId");
            return (Criteria) this;
        }

        public Criteria andSppIdIsNull() {
            addCriterion("spp_id is null");
            return (Criteria) this;
        }

        public Criteria andSppIdIsNotNull() {
            addCriterion("spp_id is not null");
            return (Criteria) this;
        }

        public Criteria andSppIdEqualTo(Integer value) {
            addCriterion("spp_id =", value, "sppId");
            return (Criteria) this;
        }

        public Criteria andSppIdNotEqualTo(Integer value) {
            addCriterion("spp_id <>", value, "sppId");
            return (Criteria) this;
        }

        public Criteria andSppIdGreaterThan(Integer value) {
            addCriterion("spp_id >", value, "sppId");
            return (Criteria) this;
        }

        public Criteria andSppIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("spp_id >=", value, "sppId");
            return (Criteria) this;
        }

        public Criteria andSppIdLessThan(Integer value) {
            addCriterion("spp_id <", value, "sppId");
            return (Criteria) this;
        }

        public Criteria andSppIdLessThanOrEqualTo(Integer value) {
            addCriterion("spp_id <=", value, "sppId");
            return (Criteria) this;
        }

        public Criteria andSppIdIn(List<Integer> values) {
            addCriterion("spp_id in", values, "sppId");
            return (Criteria) this;
        }

        public Criteria andSppIdNotIn(List<Integer> values) {
            addCriterion("spp_id not in", values, "sppId");
            return (Criteria) this;
        }

        public Criteria andSppIdBetween(Integer value1, Integer value2) {
            addCriterion("spp_id between", value1, value2, "sppId");
            return (Criteria) this;
        }

        public Criteria andSppIdNotBetween(Integer value1, Integer value2) {
            addCriterion("spp_id not between", value1, value2, "sppId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNumericIsNull() {
            addCriterion("numeric is null");
            return (Criteria) this;
        }

        public Criteria andNumericIsNotNull() {
            addCriterion("numeric is not null");
            return (Criteria) this;
        }

        public Criteria andNumericEqualTo(Byte value) {
            addCriterion("numeric =", value, "numeric");
            return (Criteria) this;
        }

        public Criteria andNumericNotEqualTo(Byte value) {
            addCriterion("numeric <>", value, "numeric");
            return (Criteria) this;
        }

        public Criteria andNumericGreaterThan(Byte value) {
            addCriterion("numeric >", value, "numeric");
            return (Criteria) this;
        }

        public Criteria andNumericGreaterThanOrEqualTo(Byte value) {
            addCriterion("numeric >=", value, "numeric");
            return (Criteria) this;
        }

        public Criteria andNumericLessThan(Byte value) {
            addCriterion("numeric <", value, "numeric");
            return (Criteria) this;
        }

        public Criteria andNumericLessThanOrEqualTo(Byte value) {
            addCriterion("numeric <=", value, "numeric");
            return (Criteria) this;
        }

        public Criteria andNumericIn(List<Byte> values) {
            addCriterion("numeric in", values, "numeric");
            return (Criteria) this;
        }

        public Criteria andNumericNotIn(List<Byte> values) {
            addCriterion("numeric not in", values, "numeric");
            return (Criteria) this;
        }

        public Criteria andNumericBetween(Byte value1, Byte value2) {
            addCriterion("numeric between", value1, value2, "numeric");
            return (Criteria) this;
        }

        public Criteria andNumericNotBetween(Byte value1, Byte value2) {
            addCriterion("numeric not between", value1, value2, "numeric");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("unit is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("unit is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("unit =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("unit <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("unit >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("unit >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("unit <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("unit <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("unit like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotLike(String value) {
            addCriterion("unit not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("unit in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("unit not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("unit between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("unit not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andGenericIsNull() {
            addCriterion("generic is null");
            return (Criteria) this;
        }

        public Criteria andGenericIsNotNull() {
            addCriterion("generic is not null");
            return (Criteria) this;
        }

        public Criteria andGenericEqualTo(Byte value) {
            addCriterion("generic =", value, "generic");
            return (Criteria) this;
        }

        public Criteria andGenericNotEqualTo(Byte value) {
            addCriterion("generic <>", value, "generic");
            return (Criteria) this;
        }

        public Criteria andGenericGreaterThan(Byte value) {
            addCriterion("generic >", value, "generic");
            return (Criteria) this;
        }

        public Criteria andGenericGreaterThanOrEqualTo(Byte value) {
            addCriterion("generic >=", value, "generic");
            return (Criteria) this;
        }

        public Criteria andGenericLessThan(Byte value) {
            addCriterion("generic <", value, "generic");
            return (Criteria) this;
        }

        public Criteria andGenericLessThanOrEqualTo(Byte value) {
            addCriterion("generic <=", value, "generic");
            return (Criteria) this;
        }

        public Criteria andGenericIn(List<Byte> values) {
            addCriterion("generic in", values, "generic");
            return (Criteria) this;
        }

        public Criteria andGenericNotIn(List<Byte> values) {
            addCriterion("generic not in", values, "generic");
            return (Criteria) this;
        }

        public Criteria andGenericBetween(Byte value1, Byte value2) {
            addCriterion("generic between", value1, value2, "generic");
            return (Criteria) this;
        }

        public Criteria andGenericNotBetween(Byte value1, Byte value2) {
            addCriterion("generic not between", value1, value2, "generic");
            return (Criteria) this;
        }

        public Criteria andSearchingIsNull() {
            addCriterion("searching is null");
            return (Criteria) this;
        }

        public Criteria andSearchingIsNotNull() {
            addCriterion("searching is not null");
            return (Criteria) this;
        }

        public Criteria andSearchingEqualTo(Byte value) {
            addCriterion("searching =", value, "searching");
            return (Criteria) this;
        }

        public Criteria andSearchingNotEqualTo(Byte value) {
            addCriterion("searching <>", value, "searching");
            return (Criteria) this;
        }

        public Criteria andSearchingGreaterThan(Byte value) {
            addCriterion("searching >", value, "searching");
            return (Criteria) this;
        }

        public Criteria andSearchingGreaterThanOrEqualTo(Byte value) {
            addCriterion("searching >=", value, "searching");
            return (Criteria) this;
        }

        public Criteria andSearchingLessThan(Byte value) {
            addCriterion("searching <", value, "searching");
            return (Criteria) this;
        }

        public Criteria andSearchingLessThanOrEqualTo(Byte value) {
            addCriterion("searching <=", value, "searching");
            return (Criteria) this;
        }

        public Criteria andSearchingIn(List<Byte> values) {
            addCriterion("searching in", values, "searching");
            return (Criteria) this;
        }

        public Criteria andSearchingNotIn(List<Byte> values) {
            addCriterion("searching not in", values, "searching");
            return (Criteria) this;
        }

        public Criteria andSearchingBetween(Byte value1, Byte value2) {
            addCriterion("searching between", value1, value2, "searching");
            return (Criteria) this;
        }

        public Criteria andSearchingNotBetween(Byte value1, Byte value2) {
            addCriterion("searching not between", value1, value2, "searching");
            return (Criteria) this;
        }

        public Criteria andSegementsIsNull() {
            addCriterion("segements is null");
            return (Criteria) this;
        }

        public Criteria andSegementsIsNotNull() {
            addCriterion("segements is not null");
            return (Criteria) this;
        }

        public Criteria andSegementsEqualTo(String value) {
            addCriterion("segements =", value, "segements");
            return (Criteria) this;
        }

        public Criteria andSegementsNotEqualTo(String value) {
            addCriterion("segements <>", value, "segements");
            return (Criteria) this;
        }

        public Criteria andSegementsGreaterThan(String value) {
            addCriterion("segements >", value, "segements");
            return (Criteria) this;
        }

        public Criteria andSegementsGreaterThanOrEqualTo(String value) {
            addCriterion("segements >=", value, "segements");
            return (Criteria) this;
        }

        public Criteria andSegementsLessThan(String value) {
            addCriterion("segements <", value, "segements");
            return (Criteria) this;
        }

        public Criteria andSegementsLessThanOrEqualTo(String value) {
            addCriterion("segements <=", value, "segements");
            return (Criteria) this;
        }

        public Criteria andSegementsLike(String value) {
            addCriterion("segements like", value, "segements");
            return (Criteria) this;
        }

        public Criteria andSegementsNotLike(String value) {
            addCriterion("segements not like", value, "segements");
            return (Criteria) this;
        }

        public Criteria andSegementsIn(List<String> values) {
            addCriterion("segements in", values, "segements");
            return (Criteria) this;
        }

        public Criteria andSegementsNotIn(List<String> values) {
            addCriterion("segements not in", values, "segements");
            return (Criteria) this;
        }

        public Criteria andSegementsBetween(String value1, String value2) {
            addCriterion("segements between", value1, value2, "segements");
            return (Criteria) this;
        }

        public Criteria andSegementsNotBetween(String value1, String value2) {
            addCriterion("segements not between", value1, value2, "segements");
            return (Criteria) this;
        }

        public Criteria andValueIsNull() {
            addCriterion("value is null");
            return (Criteria) this;
        }

        public Criteria andValueIsNotNull() {
            addCriterion("value is not null");
            return (Criteria) this;
        }

        public Criteria andValueEqualTo(Integer value) {
            addCriterion("value =", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotEqualTo(Integer value) {
            addCriterion("value <>", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThan(Integer value) {
            addCriterion("value >", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThanOrEqualTo(Integer value) {
            addCriterion("value >=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThan(Integer value) {
            addCriterion("value <", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThanOrEqualTo(Integer value) {
            addCriterion("value <=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueIn(List<Integer> values) {
            addCriterion("value in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotIn(List<Integer> values) {
            addCriterion("value not in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueBetween(Integer value1, Integer value2) {
            addCriterion("value between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotBetween(Integer value1, Integer value2) {
            addCriterion("value not between", value1, value2, "value");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_spec_param_use
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 02 12:30:15 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
