package com.bupt.core.dao;

import com.bupt.core.entity.Category;
import com.bupt.core.entity.CategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_use
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    long countByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_use
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    int deleteByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_use
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_use
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_use
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_use
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    List<Category> selectByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_use
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_use
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_use
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    int updateByExample(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_use
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_use
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    int updateByPrimaryKey(Category record);

    /**
     * 获取平级的子分类
     * @param parentId
     * @return
     */
    List<Category> selectParallelChildrenCategory(int parentId);
}
