package com.bupt.core.dao;

import com.bupt.core.entity.ParamOption;
import com.bupt.core.entity.ParamOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParamOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param_options
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    long countByExample(ParamOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param_options
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    int deleteByExample(ParamOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param_options
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param_options
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    int insert(ParamOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param_options
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    int insertSelective(ParamOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param_options
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    List<ParamOption> selectByExample(ParamOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param_options
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    ParamOption selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param_options
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") ParamOption record, @Param("example") ParamOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param_options
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    int updateByExample(@Param("record") ParamOption record, @Param("example") ParamOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param_options
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    int updateByPrimaryKeySelective(ParamOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param_options
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    int updateByPrimaryKey(ParamOption record);
}
