package com.bupt.core.dao;

import com.bupt.core.entity.SpecParam;
import com.bupt.core.entity.SpecParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface SpecParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    long countByExample(SpecParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    int deleteByExample(SpecParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    int insert(SpecParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    int insertSelective(SpecParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    List<SpecParam> selectByExample(SpecParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    SpecParam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") SpecParam record, @Param("example") SpecParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    int updateByExample(@Param("record") SpecParam record, @Param("example") SpecParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    int updateByPrimaryKeySelective(SpecParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spec_param_use
     *
     * @mbg.generated Tue Jun 02 12:30:15 CST 2020
     */
    int updateByPrimaryKey(SpecParam record);

    /**
     * 通过品类id查看此品类绑定的参数
     * @param groupId
     * @return
     */
    List<SpecParam> selectSpuParamByGroupId(Integer groupId);

    /**
     * 查询此商品的销售参数
     * @param groupId
     * @return
     */
    List<SpecParam> selectSaleParamByGroupId(Integer groupId);
}
