server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  service-url:
    defaultZone: http://admin:adminp@localhost:8761/eureka/


spring:
  security:
    user:
      name: admin
      password: adminp
      roles: SUPERUSER
