package com.bupt.rongsell.entity;

import java.util.Date;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_use.id
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_use.name
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_use.status
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_use.parent_id
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_use.if_parent
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    private Boolean ifParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_use.sort
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_use.create_time
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_use.update_time
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_use.id
     *
     * @return the value of t_category_use.id
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_use.id
     *
     * @param id the value for t_category_use.id
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_use.name
     *
     * @return the value of t_category_use.name
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_use.name
     *
     * @param name the value for t_category_use.name
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_use.status
     *
     * @return the value of t_category_use.status
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_use.status
     *
     * @param status the value for t_category_use.status
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_use.parent_id
     *
     * @return the value of t_category_use.parent_id
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_use.parent_id
     *
     * @param parentId the value for t_category_use.parent_id
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_use.if_parent
     *
     * @return the value of t_category_use.if_parent
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public Boolean getIfParent() {
        return ifParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_use.if_parent
     *
     * @param ifParent the value for t_category_use.if_parent
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public void setIfParent(Boolean ifParent) {
        this.ifParent = ifParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_use.sort
     *
     * @return the value of t_category_use.sort
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_use.sort
     *
     * @param sort the value for t_category_use.sort
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_use.create_time
     *
     * @return the value of t_category_use.create_time
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_use.create_time
     *
     * @param createTime the value for t_category_use.create_time
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_use.update_time
     *
     * @return the value of t_category_use.update_time
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_use.update_time
     *
     * @param updateTime the value for t_category_use.update_time
     *
     * @mbg.generated Sun May 31 13:54:55 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}