package com.bupt.rongsell.entity;

public class Group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_group_use.id
     *
     * @mbg.generated Tue Jun 02 10:26:19 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_group_use.spg_id
     *
     * @mbg.generated Tue Jun 02 10:26:19 CST 2020
     */
    private Integer spgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_group_use.name
     *
     * @mbg.generated Tue Jun 02 10:26:19 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_group_use.id
     *
     * @return the value of t_spec_group_use.id
     *
     * @mbg.generated Tue Jun 02 10:26:19 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_group_use.id
     *
     * @param id the value for t_spec_group_use.id
     *
     * @mbg.generated Tue Jun 02 10:26:19 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_group_use.spg_id
     *
     * @return the value of t_spec_group_use.spg_id
     *
     * @mbg.generated Tue Jun 02 10:26:19 CST 2020
     */
    public Integer getSpgId() {
        return spgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_group_use.spg_id
     *
     * @param spgId the value for t_spec_group_use.spg_id
     *
     * @mbg.generated Tue Jun 02 10:26:19 CST 2020
     */
    public void setSpgId(Integer spgId) {
        this.spgId = spgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_group_use.name
     *
     * @return the value of t_spec_group_use.name
     *
     * @mbg.generated Tue Jun 02 10:26:19 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_group_use.name
     *
     * @param name the value for t_spec_group_use.name
     *
     * @mbg.generated Tue Jun 02 10:26:19 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}