package com.bupt.rongsell.entity;

public class Group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_group_use.id
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_group_use.spg_id
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    private Integer spgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_group_use.name
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_group_use.parent_id
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_group_use.if_parent
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    private Boolean ifParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spec_group_use.sort
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_group_use.id
     *
     * @return the value of t_spec_group_use.id
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_group_use.id
     *
     * @param id the value for t_spec_group_use.id
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_group_use.spg_id
     *
     * @return the value of t_spec_group_use.spg_id
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    public Integer getSpgId() {
        return spgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_group_use.spg_id
     *
     * @param spgId the value for t_spec_group_use.spg_id
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    public void setSpgId(Integer spgId) {
        this.spgId = spgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_group_use.name
     *
     * @return the value of t_spec_group_use.name
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_group_use.name
     *
     * @param name the value for t_spec_group_use.name
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_group_use.parent_id
     *
     * @return the value of t_spec_group_use.parent_id
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_group_use.parent_id
     *
     * @param parentId the value for t_spec_group_use.parent_id
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_group_use.if_parent
     *
     * @return the value of t_spec_group_use.if_parent
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    public Boolean getIfParent() {
        return ifParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_group_use.if_parent
     *
     * @param ifParent the value for t_spec_group_use.if_parent
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    public void setIfParent(Boolean ifParent) {
        this.ifParent = ifParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spec_group_use.sort
     *
     * @return the value of t_spec_group_use.sort
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spec_group_use.sort
     *
     * @param sort the value for t_spec_group_use.sort
     *
     * @mbg.generated Wed Jul 08 15:18:41 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}