package com.bupt.rongsell.entity;

public class ParamOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param_options.id
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param_options.spp_id
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    private Integer sppId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param_options.name
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param_options.id
     *
     * @return the value of t_param_options.id
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_param_options.id
     *
     * @param id the value for t_param_options.id
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param_options.spp_id
     *
     * @return the value of t_param_options.spp_id
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    public Integer getSppId() {
        return sppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_param_options.spp_id
     *
     * @param sppId the value for t_param_options.spp_id
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    public void setSppId(Integer sppId) {
        this.sppId = sppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param_options.name
     *
     * @return the value of t_param_options.name
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_param_options.name
     *
     * @param name the value for t_param_options.name
     *
     * @mbg.generated Tue Jun 02 10:27:25 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}