server:
  port: 9762

spring:
  application:
    name: api-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    rongsell:
      path: /core-api/**
